### ISSUE TITLE
Referring to your repository configuration, it still doesn't work

### ISSUE THREAD

**Issue by Charles7c** [brc-dd/vitepress-with-arco#1]
Could you please help me check where the configuration is wrong? Thank you!

**Comment by Charles7c** [comment]
https://github.com/Charles7c/charles7c.github.io

**Comment by Charles7c** [comment]
Before, Arco was introduced in the way of Element Plus, dev running style and so on was fine, but errors were reported during build.
https://github.com/Charles7c/charles7c.github.io/runs/7702184010?check_suite_focus=true

**Comment by brc-dd** [comment]
Things seem to be working fine in your latest code except for some reason your global components aren't getting registered. Removing them, the build succeeds.

**Comment by Charles7c** [comment]
It's a headache. I'm a back-end developer. 
I hope I can get your help. :)

**Comment by Charles7c** [comment]
.vitepress/theme/index.ts
```
import DefaultTheme from 'vitepress/theme'
import MyLayout from "./MyLayout.vue"
import ArcoVue from '@arco-design/web-vue'
import '@arco-design/web-vue/dist/arco.css'
import './styles/vars.css'
import './styles/custom.css'
import ArticleMetadata from './components/ArticleMetadata.vue'
import Tag from './components/Tag.vue'
import Archive from './components/Archive.vue'

export default {
  ...DefaultTheme,
  Layout: MyLayout,
  enhanceApp({ app }) {
    // 全局注册ArcoDesignVue
    app.use(ArcoVue)

    app.component('ArticleMetadata', ArticleMetadata)
    app.component('Tag', Tag)
    app.component('Archive', Archive)
  }
}
```

I actually needed to introduce arco in its entirety, but I got an error building.
Can you write an example similar to the `vitepress-element-plus-demo`? 
`vitepress-arco-design-vue-demo`, yarn dev and yarn build without error.

**Comment by brc-dd** [comment]
> Can you write an example similar to the vitepress-element-plus-demo?
> vitepress-arco-design-vue-demo, yarn dev and yarn build without error.

https://github.com/brc-dd/vitepress-arco-design-vue-demo

> I actually needed to introduce arco in its entirety

This isn't recommended though. Even in my example you'll see very large chunks being generated.

**Comment by Charles7c** [comment]
![image](https://user-images.githubusercontent.com/25446948/183248067-99cb9942-915b-447c-9d10-dc50dc306be2.png)
Thank you, I have seen that I also configured like this, but it still reported an error.
Is it because I use icons alone?

**Comment by Charles7c** [comment]
oky! I deleted all my files, then added them little by little, tried dev and build again and again, and finally the problem was found to be the use of icons.
https://github.com/Charles7c/charles7c.github.io/blob/main/repos/.vitepress/theme/components/Archive.vue

**Comment by Charles7c** [comment]
I'll find out how to use its icon. thank you.
